export const TOUR_LIST_REQUEST = 'TOUR_LIST_REQUEST';
export const TOUR_LIST_SUCCESS = 'TOUR_LIST_SUCCESS';
export const TOUR_LIST_FAILURE = 'TOUR_LIST_FAILURE';

export const GET_TOUR_REQUEST = 'GET_TOUR_REQUEST';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
export const GET_TOUR_FAILURE = 'GET_TOUR_FAILURE';
