export const TOUR_CREATE_REQUEST = 'TOUR_CREATE_REQUEST';
export const TOUR_CREATE_SUCCESS = 'TOUR_CREATE_SUCCESS';
export const TOUR_CREATE_FAILURE = 'TOUR_CREATE_FAILURE';

export const GET_TOURS_REQUEST = 'GET_TOURS_REQUEST';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_FAILURE = 'GET_TOURS_FAILURE';

export const GET_TOUR_REQUEST = 'GET_TOUR_REQUEST';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
export const GET_TOUR_FAILURE = 'GET_TOUR_FAILURE';

export const DELETE_TOUR_REQUEST = 'DELETE_TOUR_REQUEST';
export const DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS';
export const DELETE_TOUR_FAILURE = 'DELETE_TOUR_FAILURE';

export const GET_USER_TOURS_REQUEST = 'GET_USER_TOURS_REQUEST';
export const GET_USER_TOURS_SUCCESS = 'GET_USER_TOURS_SUCCESS';
export const GET_USER_TOURS_FAILURE = 'GET_USER_TOURS_FAILURE';
