export const TOUR_CREATE_REQUEST = 'TOUR_CREATE_REQUEST';
export const TOUR_CREATE_SUCCESS = 'TOUR_CREATE_SUCCESS';
export const TOUR_CREATE_FAILURE = 'TOUR_CREATE_FAILURE';

export const GET_TOURS_REQUEST = 'GET_TOURS_REQUEST';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_FAILURE = 'GET_TOURS_FAILURE';
